name: Build Project

on: 
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test: 
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Generate .sln
        run: ./premake/premake5.exe vs2022 

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build project
        run: msbuild ylang.sln /p:Configuration=Release

      - name: Run Lexer tests
        run: ./bin/Release/lexer_tests/lexer_tests.exe

      - name: Run Parser tests
        run: ./bin/Release/parser_tests/parser_tests.exe

      - name: Run Value tests
        run: ./bin/Release/value_tests/value_tests.exe
