name: Build Project

on: push 

jobs:
  build-project: 
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Generate .sln
        uses: actions/generate-solution@v1
