name: Build Project

on: pull-request 


jobs:
  build-project: 
    permissions:
      contents: write
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4

      - name: msbuild:
        id: setup_msbuild_explicit
        uses: ./
        with:
          vswhere-path: "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"

      - name: setup msbuild
        id: setup_msbuild
        uses: ./

      - name: Generate solution
        uses: generate-solution@v1
      
      - name: Build app for release
        run: msbuild ylang.sln -t:rebuild -verbosity:diag -property:Configuration=Release
