name: Build Project

on: push 

jobs:
  build-project: 
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Generate .sln
        run: ./premake/premake5.exe vs2022 

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build project (Debug configuration)
        run: msbuild ylang.sln /p:Configuration=Debug 

      - name: Build project (Release configuration)
        run: msbuild ylang.sln /p:Configuration=Release





