name: Build Project

on: push 

jobs:
  build-project: 
    runs-on: "windows-latest"
    steps:
      - name: Generate .sln
        run: python3 cli.py gensln

          ## - uses: actions/checkout@v4

        ##- name: setup-msbuild
        ##  uses: microsoft/setup-msbuild@v2

          ##- name: Set up Python
          ##  uses: actions/setup-python@v2
          ##  with:
          ##    python-version: '3.10'

