name: Create Project

on: create 


jobs:
  configure-project: 
    if: github.event.ref == github.event.master_branch
    permissions:
      contents: write
      pull-requests: write
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python3 ./.github/workflows/config-premake.py ${{ github.event.repository.name }}
        # steps:
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Premake configuration with repo_name as ${{ github.event.repository.name }}"
          title: Premake Config 
          body: | # Premake config PR
            Premake file configuration with repo_name as ${{ github.event.repository.name }}
          branch: premake-config
        #create-pull-request:
        #  needs: configure-project
        #  runs-on: "windows-latest"
