name: Build Project

on: push 

jobs:
  build-project: 
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Generate solution
        uses: generate-solution@v1
      
      - name: Build app for release
        run: msbuild ylang.sln -t:rebuild -verbosity:diag -property:Configuration=Release
