name: Build Project

on: push 

jobs:
  build-project: 
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Generate .sln
        run: ./premake/premake5.exe vs2022 

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build project (Debug configuration)
        run: msbuild ylang.sln /p:Configuration=Debug 

      - name: Build project (Release configuration)
        run: msbuild ylang.sln /p:Configuration=Release

  run-tests:
    runs-on: "windows-latest"
    needs: build-project
    steps:
      - name: Run Lexer tests (Debug configuration) 
        run: ./bin/Debug/lexer_tests/lexer_tests.exe

      - name: Run Parser Tests (Debug configuration)
        run: ./bin/Debug/parser_tests/parser_tests.exe

      - name: Run Value tests (Debug configuration)
        run: ./bin/Debug/value_tests/value_tests.exe

      - name: Run Lexer tests (Release configuration)
        run: ./bin/Release/lexer_tests/lexer_tests.exe

      - name: Run Parser Tests (Release configuration)
        run: ./bin/Release/parser_tests/parser_tests.exe

      - name: Run Value tests (Release configuration)
        run: ./bin/Release/value_tests/value_tests.exe






