name: Build Project

on: push 

jobs:
  build-project: 
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Generate .sln
        run: python3 cli.py gensln

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build project
        run: msbuild /p:Configuration=Release /p:Platform="Any CPU"




